/**
 * Server-only preset registry. Imports the JSON artifact generated by
 * `web/scripts/sync-presets.mjs` from `knowledge/presets.json` (gitignored
 * source of truth synced on predev/prebuild).
 *
 * A Preset is a curated "memory preset": persona/role + a bounded set of
 * abilities (skills/tools/MCPs by catalog id). Onboarding offers presets as
 * the starting point for a user's first Memory + Worker. Ability ids use the
 * same id space as MemoryBundle abilities and resolveAbilities:
 *   - skillIds       -> skill slugs (e.g. "frontend-design") or "*"
 *   - toolIds        -> builtin tool names (e.g. "terminal") or "*"
 *   - mcpServerIds   -> MCP server names (e.g. "figma", "cursor-bridge") or "*"
 */

import presetsData from "@/data/presets.json";
import type { AgentKind } from "@/lib/user-config/schema";

export type Preset = {
	id: string;
	name: string;
	description: string;
	/** ServiceIcon slug or Mark for the card icon (optional). */
	brand?: string;
	/** Suggested runtime for the Worker built from this preset. */
	agentKind: AgentKind;
	/** Optional specialization injected into the Worker's role prompt. */
	rolePrompt: string | null;
	skillIds: string[];
	toolIds: string[];
	mcpServerIds: string[];
};

const PRESETS: ReadonlyArray<Preset> = (presetsData as Preset[]) ?? [];

/** Fresh, fully-owned copy so callers can never mutate the shared registry. */
function clone(preset: Preset): Preset {
	return {
		...preset,
		skillIds: [...preset.skillIds],
		toolIds: [...preset.toolIds],
		mcpServerIds: [...preset.mcpServerIds],
	};
}

export function listPresets(): Preset[] {
	return PRESETS.map(clone);
}

export function findPreset(id: string): Preset | null {
	const found = PRESETS.find((preset) => preset.id === id);
	return found ? clone(found) : null;
}
