/**
 * Server-only skill registry. Imports the JSON artifact generated by
 * `web/scripts/sync-skills.mjs`. The file is gitignored and regenerated
 * by `predev` / `prebuild`, so it's always in sync with the source of
 * truth at `../knowledge/skills/`.
 */

import skillsData from "@/data/skills.json";

import type { SkillDetail, SkillSummary } from "./types";

type Synced = SkillDetail;

const SKILLS: ReadonlyArray<Synced> = (skillsData as Synced[]) ?? [];

export function listSkills(): SkillSummary[] {
	return SKILLS.map(({ body: _body, ...rest }) => rest);
}

export function findSkill(slug: string): SkillDetail | null {
	return SKILLS.find((s) => s.slug === slug) ?? null;
}

export function skillCategories(): string[] {
	const set = new Set<string>();
	for (const s of SKILLS) set.add(s.category);
	return [...set].sort();
}
