/**
 * Memory bundle factory + resolution. Server-only (imports the bundled
 * default-bundle JSON + the ability catalogs).
 *
 * The seeded default bundle (id `DEFAULT_MEMORY_BUNDLE_ID`) is synthesized
 * from `web/data/memory-default.json` (generated by sync-memory.mjs from the
 * repo's knowledge/ persona files) rather than persisted, so every account
 * always starts with it without a DB write or client-bundle bloat.
 */

import { randomUUID } from "node:crypto";

import memoryDefault from "@/data/memory-default.json";
import {
	DEFAULT_MEMORY_BUNDLE_ID,
	type MemoryBundle,
	type MemoryBundleDocs,
	type MemoryBundleSource,
	type UserConfig,
} from "@/lib/user-config/schema";

/** Ability lists use this sentinel to mean "every item in the catalog". */
export const ABILITY_WILDCARD = "*";

const EPOCH = new Date(0).toISOString();

export function defaultBundleDocs(): MemoryBundleDocs {
	const d = memoryDefault as Partial<MemoryBundleDocs>;
	return {
		soul: d.soul ?? "",
		agentDocs: d.agentDocs ?? "",
		memory: d.memory ?? "",
		user: d.user ?? "",
	};
}

/** The seeded "Agent Machines default" bundle — full ability set + the
 *  knowledge/ persona docs. */
export function defaultMemoryBundle(): MemoryBundle {
	return {
		id: DEFAULT_MEMORY_BUNDLE_ID,
		name: "Agent Machines default",
		description:
			"Your starting owned memory: persona, operating rules, agent docs, and the full ability set.",
		source: "default",
		docs: defaultBundleDocs(),
		skillIds: [ABILITY_WILDCARD],
		toolIds: [ABILITY_WILDCARD],
		mcpServerIds: [ABILITY_WILDCARD],
		createdAt: EPOCH,
		updatedAt: EPOCH,
	};
}

/**
 * All bundles for a user, always including the seeded default first — unless
 * the user has customized it (a stored bundle under the same id replaces it).
 */
export function listBundles(config: UserConfig): MemoryBundle[] {
	const stored = config.memoryBundles ?? [];
	if (stored.some((b) => b.id === DEFAULT_MEMORY_BUNDLE_ID)) return stored;
	return [defaultMemoryBundle(), ...stored];
}

export function resolveBundle(
	config: UserConfig,
	id: string | null | undefined,
): MemoryBundle | null {
	if (!id) return null;
	const stored = (config.memoryBundles ?? []).find((b) => b.id === id);
	if (stored) return stored;
	if (id === DEFAULT_MEMORY_BUNDLE_ID) return defaultMemoryBundle();
	return null;
}

export type NewBundleInput = {
	name: string;
	description?: string;
	docs?: Partial<MemoryBundleDocs>;
	skillIds?: string[];
	toolIds?: string[];
	mcpServerIds?: string[];
	source?: MemoryBundleSource;
};

export function newBundle(input: NewBundleInput): MemoryBundle {
	const now = new Date().toISOString();
	return {
		id: randomUUID(),
		name: input.name.trim() || "Untitled bundle",
		description: input.description ?? "",
		source: input.source ?? "custom",
		docs: {
			soul: input.docs?.soul ?? "",
			agentDocs: input.docs?.agentDocs ?? "",
			memory: input.docs?.memory ?? "",
			user: input.docs?.user ?? "",
		},
		skillIds: input.skillIds ?? [ABILITY_WILDCARD],
		toolIds: input.toolIds ?? [ABILITY_WILDCARD],
		mcpServerIds: input.mcpServerIds ?? [ABILITY_WILDCARD],
		createdAt: now,
		updatedAt: now,
	};
}
